Avoid build error due to boost 1.79 on modern mac
```
In file included from /Users/julien/.conan/data/boost/1.79.0/_/_/package/29ad51d914f41600a5cbc40701ebc9c992c0f7fc/include/boost/type_index/stl_type_index.hpp:47:
/Users/julien/.conan/data/boost/1.79.0/_/_/package/29ad51d914f41600a5cbc40701ebc9c992c0f7fc/include/boost/container_hash/hash.hpp:132:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
1 error generated.
```